### PR TITLE
Security Bug AWS password in debug log

### PR DESCRIPTION
**Pull request by mdegerne**
This replaces secret with "(redacted)"

### CODE REVIEW

**Comment by mdegerne** [comment]
Tested locally - may still want tests, just not sure how best to do them.

**Comment by notmyname** [comment]
alternatively, we could do something similar as upstream swift (and even use the same method)

**Comment by notmyname** [comment]
ah, it was https://review.openstack.org/#/c/548948/7/swift/common/middleware/proxy_logging.py that I was thinking more of. Unfortunately not landed yet.

**Comment by timuralp** [comment]
@mdegerne looks good. I think we can write a unit test fairly easily that verifies that the secret is replaced using a logger mock?

**Comment by mdegerne** [comment]
I'll squash, just wanted to make it easy to read.

**Pull request merged**
